const projects = [
  {
    num: 1,
    name: 'Udit Sen',
    email: 'udisen97@gmail.com',
    contact: 9826942288,
    profile: 'aedit',
    projectrepo: 'aedit/gdgcloudprojects',
  },
  {
    num: 2,
    name: 'OMKAR AGRAWAL',
    email: 'omkar3654@gmail.com',
    contact: 7977937694,
    profile: 'omkaragrawal',
    projectrepo: 'gdg-cloud-indore/catchup-web',
  },
  {
    num: 3,
    name: 'Aman Kumar',
    email: 'thisisamank@gmail.com',
    contact: 7050938325,
    profile: 'thisisamank',
    projectrepo: 'gdg-cloud-indore/course-ops',
  },
  {
    num: 4,
    name: 'Aniruddh Parwal',
    email: 'aniruddhparwal@gmail.com',
    contact: 9752225100,
    profile: 'aniruddhparwal',
    projectrepo: 'gdg-cloud-indore/contactwithoutnetwork',
  },
  {
    num: 5,
    name: 'Harshit Jain',
    email: 'harshitjain1309@gmail.com',
    contact: 9479756888,
    profile: 'iharshit009',
    projectrepo: 'gdg-cloud-indore/naarad',
  },
  {
    num: 6,
    name: 'Tushar Sadhwani',
    email: 'tushar.sadhwani000@gmail.com',
    contact: 8982807656,
    profile: 'tusharsadhwani',
    projectrepo: 'gdg-cloud-indore/cslabs',
  },
]
